__name__="nervaluate"
__version__="0.1.2"
__description__="NER evaluation done right"
__url__="https://www.github.com/ivyleavedtoadflax/nervaluate"
__author__="David Batista and Matthew Upson"
__author_email__="david.batista@gmail.com and matthew.a.upson@gmail.com"
__license__="GNU GPL v3"
