__name__="nervaluate"
__version__="0.1.5"
__description__="NER evaluation done right"
__url__="https://pypi.org/project/nervaluate"
__author__="David Batista, Matthew Upson"
__author_email__="david.batista@gmail.com,matthew.a.upson@gmail.com"
__license__="GNU GPL v3"
