name: CI Code Checks
# This workflow is currently disabled and will only run manually
# To run: Go to Actions tab -> Select this workflow -> Run workflow
on:
  workflow_dispatch:
  # Disabled automatic triggers
  # pull_request:

permissions:
  contents: write
jobs:
  build:
    name: code checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"

    - name: Checking formatting and analysing the code with pylint and flake8
      run: make lint

    - name: Running tests
      run: make test

    - name: Type checking with mypy
      run: mypy --config setup.cfg src
